create table tb_permission (id int8 generated by default as identity, description varchar(255) not null, name varchar(255) not null, primary key (id));
create table tb_group (id int8 generated by default as identity, name varchar(255) not null, primary key (id));
create table tb_group_permission (group_id int8 not null, permission_id int8 not null, primary key (group_id, permission_id));
create table tb_user (id int8 generated by default as identity, created_at datetime not null, email varchar(255) not null, first_name varchar(255) not null, last_name varchar(255) not null, password varchar(255) not null, updated_at datetime not null, primary key (id));
create table tb_user_group (user_id int8 not null, group_id int8 not null, primary key (user_id, group_id));
alter table if exists tb_group_permission add constraint FKc2rc154h8udl1bmo76luik7jj foreign key (permission_id) references tb_permission;
alter table if exists tb_group_permission add constraint FKfabw19737lr4x9u74m9bhs9cx foreign key (group_id) references tb_group;
alter table if exists tb_user_group add constraint FKid96lv86ri5sahn1i5vfutj7u foreign key (group_id) references tb_group;
alter table if exists tb_user_group add constraint FK2jb7cj4c0qrsqutdjr9wpuo6l foreign key (user_id) references tb_user;
